export const GALLERY_FILTERS = ["All", "Beaches", "Mountains", "Adventure", "Cities"];

export interface GalleryItem {
  id: string;
  src: string;
  alt: string;
  title: string;
  location: string;
  category: string;
}

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "item-1",
    src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    alt: "Golden Beach Sunset",
    title: "Pristine Sunset Coast",
    location: "Goa, India",
    category: "Beaches",
  },
  {
    id: "item-2",
    src: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=600&q=80",
    alt: "Majestic Alpine Lake",
    title: "Emerald Mountain Lake",
    location: "Himachal Pradesh, India",
    category: "Mountains",
  },
  {
    id: "item-3",
    src: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=600&q=80",
    alt: "Scenic Travel Boat Cruise",
    title: "Vibrant River Cruise",
    location: "Kerala Backwaters, India",
    category: "Adventure",
  },
  {
    id: "item-4",
    src: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=600&q=80",
    alt: "Red Rocks Desert Canyons",
    title: "Deep Valley Canyons",
    location: "Ladakh, India",
    category: "Mountains",
  },
  {
    id: "item-5",
    src: "https://images.unsplash.com/photo-1548777123-e216912df7d8?auto=format&fit=crop&w=600&q=80",
    alt: "Snow Mountain Peak Trekking",
    title: "Glacier Summit Trek",
    location: "Uttarakhand, India",
    category: "Adventure",
  },
  {
    id: "item-6",
    src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    alt: "Valley Mountain Waterfall Rivers",
    title: "Misty Mountain Falls",
    location: "Meghalaya, India",
    category: "Mountains",
  },
  {
    id: "item-7",
    src: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80",
    alt: "Historic Taj Mahal Palace",
    title: "Royal Taj Mahal Heritage",
    location: "Agra, India",
    category: "Cities",
  },
  {
    id: "item-8",
    src: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=600&q=80",
    alt: "Warm Starry Campfire Mountain Night",
    title: "Under the Alpine Stars",
    location: "Spiti Valley, India",
    category: "Adventure",
  },
  {
    id: "item-9",
    src: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=600&q=80",
    alt: "Goa Beach Palms",
    title: "Tropical Palms Cove",
    location: "Goa, India",
    category: "Beaches",
  },
  {
    id: "item-10",
    src: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=600&q=80",
    alt: "Beautiful Coastal Shore",
    title: "Turquoise Waves Shoreline",
    location: "Andaman Islands, India",
    category: "Beaches",
  },
  {
    id: "item-11",
    src: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80",
    alt: "Secluded Lagoon",
    title: "Hidden Exotic Lagoon",
    location: "Havelock Island, India",
    category: "Beaches",
  },
  {
    id: "item-12",
    src: "https://images.unsplash.com/photo-1473116763269-255448993f36?auto=format&fit=crop&w=600&q=80",
    alt: "White Sand Beach Sunrise",
    title: "Pristine White Sands",
    location: "Lakshadweep, India",
    category: "Beaches",
  },
  {
    id: "item-13",
    src: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    alt: "Snow-capped Mountain Ridge",
    title: "Majestic Peaks Range",
    location: "Gulmarg, India",
    category: "Mountains",
  },
  {
    id: "item-14",
    src: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=600&q=80",
    alt: "High Mountain Plateau",
    title: "Eternal Snowline Passes",
    location: "Leh Ladakh, India",
    category: "Mountains",
  },
  {
    id: "item-15",
    src: "https://images.unsplash.com/photo-1486873249359-2731bd6dafc7?auto=format&fit=crop&w=600&q=80",
    alt: "Stunning Sunlit Peak",
    title: "Golden Hour Ridgeline",
    location: "Manali, India",
    category: "Mountains",
  },
  {
    id: "item-16",
    src: "https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9?auto=format&fit=crop&w=600&q=80",
    alt: "Himalayan Foothills Village",
    title: "Peaceful Valley Settlements",
    location: "Dharamshala, India",
    category: "Mountains",
  },
  {
    id: "item-17",
    src: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80",
    alt: "Vibrant Jaipur Palace",
    title: "Vibrant Palace Courtyards",
    location: "Jaipur, India",
    category: "Cities",
  },
  {
    id: "item-18",
    src: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=600&q=80",
    alt: "Heritage Temple Architecture",
    title: "Ancient Carved Pillars",
    location: "Hampi, India",
    category: "Cities",
  },
  {
    id: "item-19",
    src: "https://images.unsplash.com/photo-1590050752117-238cb0612b1b?auto=format&fit=crop&w=600&q=80",
    alt: "Lake Palace at Dusk",
    title: "Floating Heritage Palace",
    location: "Udaipur, India",
    category: "Cities",
  },
  {
    id: "item-20",
    src: "https://images.unsplash.com/photo-1598977123418-45f04b614088?auto=format&fit=crop&w=600&q=80",
    alt: "Majestic Fort Walls",
    title: "Historic Amber Fort",
    location: "Jaipur, India",
    category: "Cities",
  },
  {
    id: "item-21",
    src: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80",
    alt: "Whitewater River Rafting",
    title: "Raging Ganges Rapids",
    location: "Rishikesh, India",
    category: "Adventure",
  },
  {
    id: "item-22",
    src: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80",
    alt: "Forest Camping Under Canopy",
    title: "Wild Canopy Camping",
    location: "Jim Corbett, India",
    category: "Adventure",
  },
  {
    id: "item-23",
    src: "https://images.unsplash.com/photo-1530731141654-5961fa6f698e?auto=format&fit=crop&w=600&q=80",
    alt: "Mountain Pass Bike Expedition",
    title: "High Altitude Biking",
    location: "Khardung La, India",
    category: "Adventure",
  },
  {
    id: "item-24",
    src: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?auto=format&fit=crop&w=600&q=80",
    alt: "Desert Safari Sunset Camel",
    title: "Desert Sunset Caravans",
    location: "Jaisalmer, India",
    category: "Adventure",
  },
  {
    id: "item-25",
    src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    alt: "Verdant Green Hills",
    title: "Lush Tea Plantations",
    location: "Munnar, India",
    category: "Mountains",
  },
  {
    id: "item-26",
    src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    alt: "Sunset Palm Beach",
    title: "Serene Coconut Shallows",
    location: "Varkala, India",
    category: "Beaches",
  },
  {
    id: "item-27",
    src: "https://images.unsplash.com/photo-1473116763269-255448993f36?auto=format&fit=crop&w=600&q=80",
    alt: "Corals Shoreline",
    title: "Marine Coral Reef Coast",
    location: "Neil Island, India",
    category: "Beaches",
  },
  {
    id: "item-28",
    src: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=600&q=80",
    alt: "Akshardham Temple Night",
    title: "Spiritual Light show",
    location: "Delhi, India",
    category: "Cities",
  },
  {
    id: "item-29",
    src: "https://images.unsplash.com/photo-1590050752117-238cb0612b1b?auto=format&fit=crop&w=600&q=80",
    alt: "Ghats of Varanasi at Sunrise",
    title: "Subah-e-Banaras Ghats",
    location: "Varanasi, India",
    category: "Cities",
  },
  {
    id: "item-30",
    src: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80",
    alt: "Paragliding in Solang Valley",
    title: "Himalayan Sky Gliding",
    location: "Bir Billing, India",
    category: "Adventure",
  },
];
