import type { Metadata } from "next";

import { AppProvider } from "@/context/AppContext";
import QueryProvider from "@/providers/QueryProvider";

import { ErrorBoundary } from "@/components/common/ErrorBoundary";

import { inter, outfit, poppins } from "@/styles/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${outfit.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ErrorBoundary>
          <QueryProvider>
            <AppProvider>{children}</AppProvider>
          </QueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
